// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awuvfvubtmxegpqfddbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3dXZmdnVidG14ZWdwcWZkZGJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MzQzNjksImV4cCI6MjA3MjIxMDM2OX0.0WXJCxqpsV8pl6qW4Lx1FZIV367kzB8lxh85LhlhVKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});